# Generated by Django 5.2.1 on 2025-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок статьи"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="URL-адрес")),
                ("content", models.TextField(verbose_name="Содержание статьи")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья: Чтение статистик",
                "verbose_name_plural": "Статьи: Чтение статистик",
            },
        ),
        migrations.DeleteModel(
            name="TheoryArticle",
        ),
    ]
