# Generated by Django 5.2.1 on 2025-05-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0002_statisticsarticle_delete_theoryarticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=150, verbose_name="Термин")),
                ("definition", models.TextField(verbose_name="Определение")),
                ("slug", models.SlugField(unique=True, verbose_name="URL-адрес")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Термин глоссария",
                "verbose_name_plural": "Термины глоссария",
            },
        ),
    ]
