# Generated by Django 5.2.1 on 2025-05-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theory", "0003_glossaryterm"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticsarticle",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Видео (ВК / Rutube)"
            ),
        ),
    ]
