# Generated by Django 5.2.1 on 2025-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userreport",
            name="output_file",
        ),
        migrations.AddField(
            model_name="userreport",
            name="file_name",
            field=models.CharField(default="Separated_Art_Rep.xlsx", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userreport",
            name="file_path",
            field=models.CharField(
                default="user_reports/0/Separated_Art_Rep.xlsx", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userreport",
            name="report_type",
            field=models.CharField(
                choices=[("form4", "Накопительный отчёт"), ("form5", "Остатки")],
                default="form4",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
