# Generated by Django 5.2.1 on 2025-06-25 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "forms_app",
            "0002_remove_userreport_output_file_userreport_file_name_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_full_name",
                    models.CharField(max_length=255, verbose_name="Артикул поставщика"),
                ),
                ("size", models.CharField(max_length=10, verbose_name="Размер")),
                ("quantity", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="Не указано",
                        max_length=100,
                        null=True,
                        verbose_name="Место хранения",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Примечание"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Складская запись",
                "verbose_name_plural": "Складские записи",
            },
        ),
    ]
