# Generated by Django 5.2.1 on 2025-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0003_stockrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_name", models.CharField(max_length=50, verbose_name="Неделя")),
                (
                    "art_group",
                    models.CharField(max_length=3, verbose_name="Группа артикулов"),
                ),
                ("profit", models.FloatField(verbose_name="Прибыль")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
