# Generated by Django 5.2.1 on 2025-07-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0004_weeklyreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form4Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, verbose_name="Код номенклатуры"),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Артикул"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "clear_sales_our",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Чистые продажи Наши"
                    ),
                ),
                (
                    "clear_sales_vb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Чистая реализация ВБ"
                    ),
                ),
                (
                    "clear_transfer",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Чистое Перечисление"
                    ),
                ),
                (
                    "clear_transfer_without_log",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Чистое Перечисление без Логистики",
                    ),
                ),
                (
                    "our_price_mid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Наша цена Средняя"
                    ),
                ),
                (
                    "vb_selling_mid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Реализация ВБ Средняя"
                    ),
                ),
                (
                    "transfer_mid",
                    models.FloatField(
                        blank=True, null=True, verbose_name="К перечислению Среднее"
                    ),
                ),
                (
                    "transfer_without_log_mid",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="К Перечислению без Логистики Средняя",
                    ),
                ),
                (
                    "qentity_sale",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Чистые продажи, шт"
                    ),
                ),
                (
                    "sebes_sale",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Себес Продаж (600р)"
                    ),
                ),
                (
                    "profit_1",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Прибыль на 1 Юбку"
                    ),
                ),
                (
                    "percent_sell",
                    models.FloatField(blank=True, null=True, verbose_name="%Выкупа"),
                ),
                (
                    "profit",
                    models.FloatField(blank=True, null=True, verbose_name="Прибыль"),
                ),
                (
                    "orders",
                    models.IntegerField(blank=True, null=True, verbose_name="Заказы"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form4_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма 4: Накопительный отчёт",
                "verbose_name_plural": "Форма 4: Накопительные отчёты",
                "unique_together": {("user", "code", "date")},
            },
        ),
    ]
