# Generated by Django 5.2.1 on 2025-08-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0005_form4data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form8Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_name", models.CharField(max_length=100, verbose_name="Неделя")),
                (
                    "date_extracted",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата из файла"
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Прибыль",
                    ),
                ),
                (
                    "clean_sales_ours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Чистые продажи Наши",
                    ),
                ),
                (
                    "orders",
                    models.IntegerField(blank=True, null=True, verbose_name="Заказы"),
                ),
                (
                    "spp_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% СПП",
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Наша цена Средняя",
                    ),
                ),
                (
                    "profit_per_skirt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Прибыль на 1 Юбку",
                    ),
                ),
                (
                    "pickup_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% Выкупа",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Отчёт Формы 8",
                "verbose_name_plural": "Форма 8 — Недельные метрики",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
