# Generated by Django 5.2.1 on 2025-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0008_weeklyreport_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="form4data",
            name="percent_log_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="% Лог/Наша Цена"
            ),
        ),
    ]
