# Generated by Django 5.2.1 on 2025-11-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0009_form4data_percent_log_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form12Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wb_article",
                    models.CharField(max_length=100, verbose_name="Артикул WB"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Баркод"
                    ),
                ),
                (
                    "seller_article",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Артикул продавца",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Размер"
                    ),
                ),
                (
                    "orders_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Заказы, шт."
                    ),
                ),
                (
                    "order_amount_net",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Сумма заказов минус комиссия WB, руб.",
                    ),
                ),
                (
                    "sold_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Выкупили, шт."
                    ),
                ),
                (
                    "transfer_amount",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="К перечислению за товар, руб.",
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Текущий остаток, шт."
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата отчёта")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные формы 12",
                "verbose_name_plural": "Данные формы 12",
                "ordering": ["-date"],
            },
        ),
    ]
