# Generated by Django 5.2.1 on 2025-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0010_form12data"),
    ]

    operations = [
        migrations.AddField(
            model_name="form4data",
            name="spp_percent",
            field=models.FloatField(blank=True, null=True, verbose_name="% СПП"),
        ),
    ]
