# Generated by Django 5.2.1 on 2025-12-08 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0011_form4data_spp_percent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form14Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата отчета")),
                (
                    "total_orders_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Всего заказов, шт."
                    ),
                ),
                (
                    "total_order_amount_net",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Общая сумма заказов минус комиссия WB, руб.",
                    ),
                ),
                (
                    "total_sold_qty",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Всего выкуплено, шт."
                    ),
                ),
                (
                    "total_transfer_amount",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Общая сумма к перечислению, руб.",
                    ),
                ),
                (
                    "total_current_stock",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Общий остаток, шт."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form14_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные формы 14",
                "verbose_name_plural": "Данные формы 14",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
