# Generated by Django 5.2.1 on 2025-12-13 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0012_form14data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pattern15",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название лекала"),
                ),
                ("width", models.IntegerField(verbose_name="Ширина (мм)")),
                ("height", models.IntegerField(verbose_name="Высота (мм)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form15_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лекало (Форма 15)",
                "verbose_name_plural": "Лекала (Форма 15)",
                "ordering": ["name"],
            },
        ),
    ]
