# Generated by Django 5.2.1 on 2025-12-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0014_form16article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="form16article",
            name="description",
        ),
        migrations.AddField(
            model_name="form16article",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Заметки и комментарии по артикулу",
                verbose_name="Комментарии",
            ),
        ),
        migrations.AddField(
            model_name="form16article",
            name="our_article",
            field=models.CharField(
                blank=True,
                help_text="Наше внутреннее название артикула",
                max_length=200,
                verbose_name="Наш артикул",
            ),
        ),
    ]
