# Generated by Django 5.2.1 on 2025-12-20 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0015_add_comments_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form16article",
            name="position",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Позиция должна быть от 1 до 30"
                    ),
                    django.core.validators.MaxValueValidator(
                        30, message="Позиция должна быть от 1 до 30"
                    ),
                ],
                verbose_name="Позиция (1-30)",
            ),
        ),
    ]
