# Generated by Django 5.2.1 on 2025-12-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0016_fix_duplicate_position_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pattern15",
            options={
                "ordering": ["pattern_number", "name"],
                "verbose_name": "Лекало (Форма 15)",
                "verbose_name_plural": "Лекала (Форма 15)",
            },
        ),
        migrations.AddField(
            model_name="pattern15",
            name="pattern_number",
            field=models.IntegerField(default=0, verbose_name="Номер лекала"),
        ),
    ]
