# Generated by Django 5.2.1 on 2025-12-31 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0018_manualchart_manualchartdatapoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualchartdatapoint",
            name="value",
        ),
        migrations.AddField(
            model_name="manualchartdatapoint",
            name="value1",
            field=models.FloatField(default=1, verbose_name="Значение 1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="manualchartdatapoint",
            name="value2",
            field=models.FloatField(blank=True, null=True, verbose_name="Значение 2"),
        ),
        migrations.AlterField(
            model_name="manualchart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
