# Generated by Django 5.2.1 on 2025-12-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0019_remove_manualchartdatapoint_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualchart",
            name="label1",
            field=models.CharField(
                default="Значение 1", max_length=100, verbose_name="Название Значения 1"
            ),
        ),
        migrations.AddField(
            model_name="manualchart",
            name="label2",
            field=models.CharField(
                blank=True,
                default="Значение 2",
                max_length=100,
                verbose_name="Название Значения 2",
            ),
        ),
    ]
