# Generated by Django 5.2.1 on 2026-01-04 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0020_manualchart_label1_manualchart_label2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wb_article",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="WB артикул"
                    ),
                ),
                (
                    "seller_article",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Артикул продавца"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Себестоимость"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Себестоимость артикула",
                "verbose_name_plural": "Себестоимости артикулов",
                "unique_together": {("user", "wb_article")},
            },
        ),
    ]
