# Generated by Django 5.2.1 on 2026-01-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0021_articlecost"),
    ]

    operations = [
        migrations.AddField(
            model_name="form8report",
            name="clean_transfer_without_logistics",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Чистое Перечисление без Логистики",
            ),
        ),
    ]
