# Generated by Django 5.2.1 on 2026-02-04 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0022_form8report_clean_transfer_without_logistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form16article",
            name="position",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Позиция должна быть от 1 до 50"
                    ),
                    django.core.validators.MaxValueValidator(
                        50, message="Позиция должна быть от 1 до 50"
                    ),
                ],
                verbose_name="Позиция (1-50)",
            ),
        ),
    ]
