# Generated by Django 5.2.1 on 2026-04-18 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0023_alter_form16article_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form20Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Код номенклатуры"
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Артикул поставщика",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="Дата отчета")),
                (
                    "clear_sales_our",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Чистые продажи Наши",
                    ),
                ),
                (
                    "clear_sales_vb",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Чистая реализация ВБ",
                    ),
                ),
                (
                    "clear_transfer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Чистое Перечисление",
                    ),
                ),
                (
                    "clear_transfer_without_log",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Чистое Перечисление без Логистики",
                    ),
                ),
                (
                    "our_price_mid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Наша цена Средняя",
                    ),
                ),
                (
                    "vb_selling_mid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Реализация ВБ Средняя",
                    ),
                ),
                (
                    "transfer_mid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="К перечислению Среднее",
                    ),
                ),
                (
                    "transfer_without_log_mid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="К Перечислению без Логистики Средняя",
                    ),
                ),
                (
                    "qentity_sale",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Чистые продажи, шт"
                    ),
                ),
                (
                    "sebes_sale",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Себес Продаж (600р)",
                    ),
                ),
                (
                    "profit_1",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Прибыль на 1 Юбку",
                    ),
                ),
                (
                    "percent_sell",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="%Выкупа",
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Прибыль",
                    ),
                ),
                (
                    "orders",
                    models.IntegerField(blank=True, null=True, verbose_name="Заказы"),
                ),
                (
                    "percent_log_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% Лог/Наша Цена",
                    ),
                ),
                (
                    "spp_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% СПП",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Форма 20 (Ежедневные данные)",
                "verbose_name_plural": "Форма 20 (Ежедневные данные)",
                "ordering": ["-date", "code"],
                "indexes": [
                    models.Index(
                        fields=["user", "code", "date"],
                        name="forms_app_f_user_id_c5a725_idx",
                    ),
                    models.Index(fields=["date"], name="forms_app_f_date_e5ac3f_idx"),
                ],
                "unique_together": {("user", "code", "date")},
            },
        ),
    ]
